#!/usr/bin/env node
/**
 * Scans public/images/ for before/after photo pairs and generates
 * src/lib/cases.generated.ts from whatever it finds. Runs automatically
 * before every `bun run build` and `bun run dev` (see package.json) --
 * you never need to edit source code to add or remove a case.
 *
 * To add a case:
 *   1. Drop case-<id>-before.jpg and case-<id>-after.jpg into public/images/
 *   2. (Optional but recommended) Add case-<id>.txt next to them:
 *        line 1 = title
 *        line 2 = meta
 *      Without this file the case still appears, just with a generic
 *      title ("Case <id>") until you add one.
 *   3. Run `bun run build` (or `bun run dev` locally) as normal.
 *
 * To remove a case, delete its two photos (and .txt, if any). It stops
 * appearing on the next build -- nothing else to touch.
 *
 * A case only appears once BOTH photos exist. A lone before or after photo
 * is reported below and skipped, rather than shown on the site as a
 * permanently broken pair.
 */
import { readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const IMAGES_DIR = path.resolve("public/images");
const OUTPUT_FILE = path.resolve("src/lib/cases.generated.ts");

const PAIR_PATTERN = /^case-(.+)-(before|after)\.(jpe?g|png)$/i;

async function readMeta(id) {
  const metaPath = path.join(IMAGES_DIR, `case-${id}.txt`);
  try {
    const text = await readFile(metaPath, "utf-8");
    const [title, meta] = text.split("\n").map((line) => line.trim());
    return {
      title: title || `Case ${id}`,
      meta: meta || "",
    };
  } catch {
    // No sidecar file yet -- still show the case, just plainly labelled.
    return { title: `Case ${id}`, meta: "" };
  }
}

function sortIds(ids) {
  // Numeric ids sort as numbers (case-2 before case-10); anything
  // non-numeric (e.g. a descriptive id) falls back to alphabetical.
  return [...ids].sort((a, b) => {
    const numA = Number(a);
    const numB = Number(b);
    if (!Number.isNaN(numA) && !Number.isNaN(numB)) return numA - numB;
    return a.localeCompare(b);
  });
}

async function main() {
  let files;
  try {
    files = await readdir(IMAGES_DIR);
  } catch {
    console.warn(`[cases] No public/images/ directory found -- writing an empty case list.`);
    files = [];
  }

  const before = new Set();
  const after = new Set();

  for (const file of files) {
    const match = file.match(PAIR_PATTERN);
    if (!match) continue;
    const [, id, side] = match;
    (side.toLowerCase() === "before" ? before : after).add(id);
  }

  const complete = sortIds([...before].filter((id) => after.has(id)));

  const missingAfter = [...before].filter((id) => !after.has(id));
  const missingBefore = [...after].filter((id) => !before.has(id));
  for (const id of missingAfter) {
    console.warn(`[cases] case-${id}-before.jpg has no matching -after photo yet -- skipped.`);
  }
  for (const id of missingBefore) {
    console.warn(`[cases] case-${id}-after.jpg has no matching -before photo yet -- skipped.`);
  }

  const cases = await Promise.all(
    complete.map(async (id) => ({ id: `case-${id}`, ...(await readMeta(id)) })),
  );

  const body = cases
    .map(
      (c) =>
        `  { id: ${JSON.stringify(c.id)}, title: ${JSON.stringify(c.title)}, meta: ${JSON.stringify(c.meta)} },`,
    )
    .join("\n");

  const output = `// Auto-generated by scripts/generate-cases.mjs -- do not edit by hand.
// Regenerated on every build from whatever photo pairs exist in
// public/images/. To add or remove a case, add or delete its photos there;
// see the comment at the top of that script for the exact steps.
import type { CaseStudy } from "./clinic";

export const GENERATED_CASES: CaseStudy[] = [
${body}
];
`;

  await writeFile(OUTPUT_FILE, output);
  console.log(`[cases] Found ${cases.length} case${cases.length === 1 ? "" : "s"}: ${cases.map((c) => c.id).join(", ") || "(none)"}`);
}

main();
